### ISSUE TITLE
No signature of method

### ISSUE THREAD

**Issue by jsukdeo** [brbeaird/SmartThings_SenseMonitor#13]
Hi Brian, great work on the Sense integration to SmartThings. I'm trying to get mine to work. I've tried to install a few times, but I'm not getting the readings. I've checked the IDE log and I see this error: 

groovy.lang.MissingMethodException: No signature of method: 

Can you assist?

Thanks,
Jay

**Comment by brbeaird** [comment]
What's the other context of that error? Can you get a line number?

**Comment by jsukdeo** [comment]
This is the full error:  error groovy.lang.MissingMethodException: No signature of method: script_app_e1863abb38f0e44b66691da4fc26884662246547afe674035d72fdeef22ceb66.senseServiceUpdate() is applicable for argument types: () values: []

**Comment by brbeaird** [comment]
Weird. What do things look like on the Node side? Does the console show that devices are being sent to the ST hub?

**Comment by jsukdeo** [comment]
Doesn't look good there...


jay@Jays-iMac node_server % node server.js
5/20/2020, 2:23:01 PM | Sense Monitor Service (v1.0.1) is Running at (IP: 192.168.140.10 | Port: 9021) | ProcessId: 1025
5/20/2020, 2:23:01 PM | FATAL ERROR: undefined
exitHandler: (PID: 1025) { exit: true } 0
jay@Jays-iMac node_server %

**Comment by brbeaird** [comment]
Yeah you need to get that part running first. I've not tried to run it on a Mac, so I'm not sure what's up there, sorry. I know a few people have had issues lately running it on newer versions of rPi's due to the SSL version the Sense API uses, so that could be part of your issue. The fix in that case was to use an older version of rPi, but I'm not sure how that would translate for you.

**Comment by jsukdeo** [comment]
Ok thanks, I'll check that out!
